title: Пишу про IT
description: Статьи о разработке и технологиях
timezone: Europe/Berlin
lang: ru

# ВАЖНО: укажите корректно url/baseurl для ссылок и метаданных
# url: "https://vdedov.github.io"
# baseurl: ""                # для персонального сайта оставьте пустым
# baseurl: "/your-blog"    # если это проектный сайт в подкаталоге

theme: minima

# Метаданные автора (для карточек, футера и SEO)
author:
  name: Владислав Дедов
  bio: Golang hазработчик. Пишу про инженерные практики, производительность и инфраструктуру.
  avatar: /assets/img/screenshot.png  # можно указать свой аватар

# markdown: kramdown
# highlighter: rouge
# kramdown:
#   input: GFM
