title: Пишу про IT
description: Статьи о разработке и технологиях

# theme: minima
# remote_theme: daattali/beautiful-jekyll
# plugins:
#   - jekyll-remote-theme
# remote_theme: daattali/beautiful-jekyll
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  
author: Vladislav Dedov
lang: ru

# Включаем меню навигации
header_pages:
  - index.md
  - about.md

# Настройки футера
show_excerpts: true
paginate: 5
paginate_path: "/page:num/"
