title: Пишу про IT
description: Статьи о разработке и технологиях
theme: daattali/beautiful-jekyll
plugins:
  - jekyll-remote-theme
author: Vladislav Dedov
lang: ru

# Включаем меню навигации
header_pages:
  - index.md
  - about.md

# Настройки футера
show_excerpts: true
